name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, osx-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore src/ezpipeline.sln
    - name: Build Net6.0
      run: dotnet publish src/ezpipeline/ezpipeline.csproj -o nuget/tools/net6.0/any/ --no-restore -f net6.0
    - name: Build Net7.0
      run: dotnet publish src/ezpipeline/ezpipeline.csproj -o nuget/tools/net7.0/any/ --no-restore -f net7.0
    - name: Fetch Butler
      run: dotnet nuget/tools/net7.0/any/ezpipeline.dll fetch-tool -n Butler -o tools/ --path
    - name: Test Butler
      run: butler help

    - name: Fetch Ninja
      run: dotnet nuget/tools/net7.0/any/ezpipeline.dll fetch-tool -n Ninja -o tools/ --path
    - name: Test Ninja
      run: ninja --version

    - name: Fetch CMake 3.19.7
      run: dotnet nuget/tools/net7.0/any/ezpipeline.dll fetch-tool -n CMake -o tools/ --path --version 3.19.7
    - name: Test CMake 3.19.7
      run: |
        echo $PATH
        output=$(cmake --version)
        echo $output
        if [[ $output != "cmake version 3.19.7"* ]]; then
            exit 1
        fi
      shell: bash
    - name: Fetch CMake 3.27.6
      run: dotnet nuget/tools/net7.0/any/ezpipeline.dll fetch-tool -n CMake -o tools/ --path --version 3.27.6
    - name: Test CMake 3.27.6
      run: |
        echo $PATH
        output=$(cmake --version)
        echo $output
        if [[ $output != "cmake version 3.27.6"* ]]; then
            exit 1
        fi
      shell: bash

        